name: Elvis Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "$GITHUB_BASE_REF"
          echo "$GITHUB_HEAD_REF"
          set +e
          curl -LO https://github.com/ayo-dele/elvis/releases/download/v0.40/elvis
          chmod +x ./elvis
          /usr/bin/git fetch --all
          /usr/bin/git checkout $GITHUB_BASE_REF
          /usr/bin/git checkout $GITHUB_HEAD_REF
          /usr/bin/git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF
          for n in $(/usr/bin/git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF); do ./elvis rock $n; done
